### ISSUE TITLE
BUg: Compilation impossible

### ISSUE THREAD

**Issue by triceratops1** [NatronVFX/openfx-community#2]
../Common/Magick/MagickPlugin.h:24:22: error fatal: Magick++.h: No existe el fichero o el directorio
 #include <Magick++.h>
                      ^
compilación terminada.

**Comment by olear** [comment]
The Magick plugins requires ImageMagick 7.x.

Note that the Looks plugin will be rewritten without ImageMagick and will be moved to openfx-arena.

**Comment by triceratops1** [comment]
https://gist.github.com/triceratops1/4b9dbc1d7a2b155e5ff196d9deb8f1b9    imagemagick 7

new bug

**Comment by olear** [comment]
pkg-config can't find ImageMagick as you see:
```
Package Magick++-7.Q32HDRI was not found in the pkg-config search path.
Perhaps you should add the directory containing `Magick++-7.Q32HDRI.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Magick++-7.Q32HDRI' found
Package Magick++-7.Q32HDRI was not found in the pkg-config search path.
Perhaps you should add the directory containing `Magick++-7.Q32HDRI.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Magick++-7.Q32HDRI' found
```

I don't know exactly what the .pc files for Magick is called on Arch.

Could you run this command:
```
pkg-config --list-all |grep Magick
```
And give me the output?

**Comment by triceratops1** [comment]
https://gist.github.com/triceratops1/b3776fc4cb2a22f5c564f3bf5c783372

**Comment by olear** [comment]
Made the build a bit more flexible, update the git repo and run this:
```
make clean
make MAGICK=Q16HDRI
```
This should match the ImageMagick version you have installed.
